included:
    - To-do
    
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Pods
    - DerivedData
    - .build

line_length: 120

disabled_rules:
    - trailing_comma
    - trailing_whitespace
    - identifier_name

function_body_length: 80

cyclomatic_complexity:
    warning: 10
    error: 10

nesting:
    type_level: 2

warning_threshold: 1
